question_data = [
        {"type": "boolean", "difficulty": "easy", "category": "Mythology",
         "question": "According to Greek Mythology, Atlas was an Olympian God.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Science: Computers",
         "question": "The Windows 7 operating system has six main editions.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "hard",
         "category": "Science: Mathematics",
         "question": "If you could fold a piece of paper in half 50 times, its&#039; thickness will be 3\/4th the distance from the Earth to the Sun.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium",
         "category": "Entertainment: Film",
         "question": "The movie &quot;Tron&quot; received an Oscar nomination for Best Visual Effects.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Politics",
         "question": "In 2016, the United Kingdom voted to stay in the EU.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Sports",
         "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Geography",
         "question": "California is larger than Japan.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Geography",
         "question": "There exists an island named &quot;Java&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Board Games",
         "question": "The Angry Video Game Nerd&#039;s alter ego is &quot;Board James&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Film",
         "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "History",
         "question": "Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium",
         "category": "Science: Computers",
         "question": "The first computer bug was formed by faulty wires.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Books",
         "question": "&quot;Elementary, my dear Watson&quot; is a phrase that is never truly said within the Conan Doyle books of Sherlock Holmes.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium",
         "category": "Science: Computers",
         "question": "MacOS is based on Linux.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Video Games",
         "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard",
         "category": "Entertainment: Video Games",
         "question": "The names of Roxas&#039;s Keyblades in Kingdom Hearts are &quot;Oathkeeper&quot; and &quot;Oblivion&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium",
         "category": "Entertainment: Video Games",
         "question": "Shang Tsung is a playable character in Mortal Kombat XL.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium",
         "category": "Entertainment: Television",
         "question": "In the TV series Red Dwarf, Kryten&#039;s full name is Kryten 2X4B-523P.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Video Games",
         "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Japanese Anime &amp; Manga",
         "question": "The anime &quot;Lucky Star&quot; follows the story of one girl who is unaware she is God.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium",
         "category": "Entertainment: Video Games",
         "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; takes place on Shadow Moses Island.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Japanese Anime &amp; Manga",
         "question": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Video Games",
         "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "General Knowledge",
         "question": "The National Animal of Scotland is the Unicorn.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "hard",
         "category": "Science &amp; Nature",
         "question": "The value of one Calorie is different than the value of one calorie.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "hard", "category": "History",
         "question": "The USS Missouri (BB-63) last served in the Korean War.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium",
         "category": "General Knowledge",
         "question": "Haggis is traditionally ate on Burns Night.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Politics",
         "question": "The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium",
         "category": "Entertainment: Video Games",
         "question": "In &quot;Team Fortress 2&quot;, the &quot;Bill&#039;s Hat&quot; is a reference to the game &quot;Dota 2&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "History",
         "question": "Adolf Hitler was a german soldier in World War I.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Film",
         "question": "&quot;Minions&quot; was released on the June 10th, 2015.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard",
         "category": "Entertainment: Music",
         "question": "The singer Billie Holiday was also known as &quot;Lady Day&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Video Games",
         "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Video Games",
         "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Video Games",
         "question": "Codemasters is the developer of the Gran Turismo series.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Geography",
         "question": "Gothenburg is the capital of Sweden.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard",
         "category": "Entertainment: Music",
         "question": "The song Scatman&#039;s World was released after Scatman (Ski-Ba-Bop-Ba-Dop-Bop).",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "hard",
         "category": "Science: Computers",
         "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium",
         "category": "Entertainment: Japanese Anime &amp; Manga",
         "question": "In &quot;To Love-Ru: Darkness&quot;, Yami reveals her real name is Eve.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Geography",
         "question": "Japan has left-hand side traffic.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Geography",
         "question": "Rhode Island is actually located on the US mainland, despite its name.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Books",
         "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel &quot;The Lord of The Rings&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium",
         "category": "Entertainment: Japanese Anime &amp; Manga",
         "question": "In &quot;JoJo&#039;s Bizarre Adventure&quot;, Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "History",
         "question": "The Spitfire originated from a racing plane.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium",
         "category": "Science &amp; Nature",
         "question": "Centripedal force is an apparent force that acts outward on a body moving around a center, arising from the body&#039;s inertia.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy",
         "category": "Entertainment: Video Games",
         "question": "In &quot;Super Mario Bros.&quot;, the clouds and bushes have the same artwork and are just different colors.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "hard",
         "category": "General Knowledge",
         "question": "Stagecoach owned &quot;South West Trains&quot; before losing the rights to FirstGroup and MTR in March of 2017.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "hard",
         "category": "Entertainment: Japanese Anime &amp; Manga",
         "question": "The character Plum from &quot;No Game No Life&quot; is a girl.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard",
         "category": "Entertainment: Video Games",
         "question": "In &quot;Minecraft&quot;, gold tools are faster than diamond tools.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium",
         "category": "Entertainment: Television",
         "question": "An episode of &quot;The Simpsons&quot; is dedicated to Moe Szyslak&#039;s bar rag.",
         "correct_answer": "True", "incorrect_answers": ["False"]}]
